version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apk-1-app
    ports:
      - "8080:8080"
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
      - ./cron/2fa-cron:/app/cron/2fa-cron:ro
      - ./scripts:/app/scripts:ro
    environment:
      - TZ=UTC
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
